# Generated by Django 5.1.7 on 2025-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longitude',
        ),
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
